### ISSUE TITLE
no_std testing is broken

### ISSUE THREAD

**Issue by csnover** [jam1garner/binrw#10]
When CI was enabled, no_std testing was added by just re-including stuff in io which was excluded by replacing `#[cfg(not(feature = "std"))]` with `#[cfg(any(not(feature = "std"), test))]`. This does not properly test no_std mode. Other places in the code also compile differently if no_std is turned on. It is necessary to actually run `cargo test --no-default-features`. Running tests with `--no-default-features` is broken currently because APIs that rely on the `std` prologue (`format!` instead of `alloc::format!`) were introduced into some tests.

**Comment by jam1garner** [comment]
Fwiw part of the reason to also include the no_std-specific code when testing std for the sake of coverage testing. (also some of the tests before had clear intent to test against no_std versions but were never run and I can't remember exactly where I fixed that but this was vaguely related). Anyways, --no-default-features works again now, thanks for pointing it out.

**Comment by csnover** [comment]
> part of the reason to also include the no_std-specific code when testing std for the sake of coverage testing

It is not necessary to do that. Please wait for a PR coming shortly.
