### ISSUE TITLE
binrw attribute breaks for raw identifiers

### ISSUE THREAD

**Issue by Swiftb0y** [jam1garner/binrw#100]
This breaks:
```rust
#[binrw]
struct Example {
    r#type: u32,
}
```
with this error:
```
custom attribute panicked
message: `"__binrw_generated_options_r#type"` is not a valid identifier
```

**Comment by dmgolembiowski** [comment]
> This breaks:
> 
> ```rust
> #[binrw]
> struct Example {
>     r#type: u32,
> }
> ```
> 
> with this error:
> 
> ```
> custom attribute panicked
> message: `"__binrw_generated_options_r#type"` is not a valid identifier
> ```

In testing a potential fix for this on a local branch, I figured a naive replacement fix could work:

```rs
pub(crate) fn make_ident(ident: &Ident, kind: &str) -> Ident {
    format_ident!(
        "__binrw_generated_{}_{}",
        kind,
        ident
            .to_string()
            .replace("__binrw_generated_options_r#", "__binrw_generated_options_")
    )   
}
```
so I tried testing it under `import { ... }` related features, since I figured they would be likely to break as well:

```rs
#[test]
fn usable_args_raw_ident() {
    #[binrw]
    struct Example {
        r#type: u32,
        flavor: ExampleFlavor,
    }   
    
    #[binrw]
    #[br(import { type: u32 })]
    enum ExampleFlavor {
        #[br(pre_assert(type == 0))]
        Zero,
        NonZero,
    }   

    let mut x = binrw::io::Cursor::new(vec![0x00, 0x00, 0x00, 0x00]);
    let example = Example::read(&mut x); 
    assert_eq!(example.flavor, ExampleFlavor::Zero);   
}
```
and we see a nice dump of compiler errors that come with this:

```sh
$ cargo test                                                                            
   Compiling binrw v0.8.4 (/home/david/code/rust/binrw/binrw)
error: custom attribute panicked
  --> binrw/tests/derive/write/import.rs:36:5
   |
36 |     #[binrw]
   |     ^^^^^^^^
   |
   = help: message: `"__binrw_generated_options_r#type"` is not a valid identifier

error: expected identifier
  --> binrw/tests/derive/write/import.rs:43:19
   |
43 |     #[br(import { type: u32 })]
   |                   ^^^^

error: expected expression
  --> binrw/tests/derive/write/import.rs:45:25
   |
45 |         #[br(pre_assert(type == 0))]
   |                         ^^^^

error: BinRead on unit-like enums requires either `#[br(repr = ...)]` on the enum or `#[br(magic = ...)]` on at least one variant
  --> binrw/tests/derive/write/import.rs:42:5
   |
42 |     #[binrw]
   |     ^^^^^^^^
   |
   = note: this error originates in the attribute macro `binrw` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared type `Example`
  --> binrw/tests/derive/write/import.rs:51:19
   |
51 |     let example = Example::read(&mut x);
   |                   ^^^^^^^ use of undeclared type `Example`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `binrw` due to 5 previous errors
```

Any ideas @jam1garner or @octylFractal?

**Comment by dmgolembiowski** [comment]
Oops

> > This breaks:
> > ```rust
> > #[binrw]
> > struct Example {
> >     r#type: u32,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with this error:
> > ```
> > custom attribute panicked
> > message: `"__binrw_generated_options_r#type"` is not a valid identifier
> > ```
> 
> In testing a potential fix for this on a local branch, I figured a naive replacement fix could work:
> 
> ```rust
> pub(crate) fn make_ident(ident: &Ident, kind: &str) -> Ident {
>     format_ident!(
>         "__binrw_generated_{}_{}",
>         kind,
>         ident
>             .to_string()
>             .replace("__binrw_generated_options_r#", "__binrw_generated_options_")
>     )   
> }
> ```
Actually I see a bug with this, maybe just `.replace("r#", "")`?

**Comment by dmgolembiowski** [comment]
Nope. Still fails to compile.

```sh
   Compiling binrw_derive v0.8.4 (/home/david/code/rust/binrw/binrw_derive)
   Compiling binrw v0.8.4 (/home/david/code/rust/binrw/binrw)
error: expected identifier
  --> binrw/tests/derive/write/import.rs:43:19
   |
43 |     #[br(import { type: u32 })]
   |                   ^^^^

error: expected expression
  --> binrw/tests/derive/write/import.rs:45:25
   |
45 |         #[br(pre_assert(type == 0))]
   |                         ^^^^

error: BinRead on unit-like enums requires either `#[br(repr = ...)]` on the enum or `#[br(magic = ...)]` on at least one variant
  --> binrw/tests/derive/write/import.rs:42:5
   |
42 |     #[binrw]
   |     ^^^^^^^^
   |
   = note: this error originates in the attribute macro `binrw` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by dmgolembiowski** [comment]
I wonder if the field `r#$name` can be internally renamed as `_r_$name` to potentially monkey-patch the generated name. Alternatively, another field decorator, like serde's `#[serde(alias = "name")]` might be appropriate for these kinds of handling cases.

**Comment by MrNbaYoh** [comment]
The problem here is we don't want to have collisions in generated names.
Taking a look at Rust identifiers (https://doc.rust-lang.org/reference/identifiers.html), we see that a valid identifier starts either with a `_` or a `XID_Start` character, or `r#` for a raw identifier.
To avoid any collision, we need to replace that `r#` sequence with another sequence that cannot be found at the beginning of a valid identifier, i.e we need to find a character that is in `XID_Continue` but not in `XID_Start` and that is different from `_`.
The only valid characters in ASCII that fulfills those conditions are numeric characters `0-9`.
Thus, we should be able to safely replace `__binrw_generated_options_r#type` with `__binrw_generated_options_0type`.

**Comment by MrNbaYoh** [comment]
> The problem here is we don't want to have collisions in generated names. Taking a look at Rust identifiers (https://doc.rust-lang.org/reference/identifiers.html), we see that a valid identifier starts either with a `_` or a `XID_Start` character, or `r#` for a raw identifier. To avoid any collision, we need to replace that `r#` sequence with another sequence that cannot be found at the beginning of a valid identifier, i.e we need to find a character that is in `XID_Continue` but not in `XID_Start` and that is different from `_`. The only valid characters in ASCII that fulfills those conditions are numeric characters `0-9`. Thus, we should be able to safely replace `__binrw_generated_options_r#type` with `__binrw_generated_options_0type`.

After some tests, there cannot be any collision actually, because one cannot use two fields `r#name` and `name` in the same struct. So just stripping the `r#` should be enough.

**Comment by Swiftb0y** [comment]
Thanks for promptly fixing the issue, even if it wasn't high priority. :+1: :heart:
