### ISSUE TITLE
Availability as an extractor in Tokio's axum

### ISSUE THREAD

**Issue by v1gnesh** [jam1garner/binrw#110]
https://tokio.rs/blog/2021-07-announcing-axum#extractors

> Requests can be parsed declaratively using "extractors".
An extractor is a type that implements FromRequest.
Extractors can be used as arguments to handlers and will run if the request URI matches.

Sounds like a perfect fit.

**Comment by v1gnesh** [comment]
Any thoughts, @jam1garner, @csnover @octylFractal ?

**Comment by octylFractal** [comment]
Are binary request bodies common? Seems like a niche use case to me, but maybe someone else has a compelling one.

**Comment by jam1garner** [comment]
I would imagine a good way to do this would be to implement a crate separate from binrw and axum that offers a FromRequest derive that bridges it to the BinRead impl, but yeah as octylFractyl said I'm not sure I see the usecase, but I do neither axum nor sending binary payloads regularly :)

**Comment by csnover** [comment]
I’m also unsure what the use case for this would be and it sounds like this could be implemented at least initially as a separate crate, so I will go ahead and just close this for now. If something compelling comes up please feel free to reopen it or add some comments!
