### ISSUE TITLE
Support moving #[br(temp)] values to later #[br(calc)] calculations.

### ISSUE THREAD

**Issue by crlf0710** [jam1garner/binrw#118]
Current this is achievable by cloning, but it would be nice if it can be supported naturally.

**Comment by rafalh** [comment]
I stepped on the same problem today (what a coincidence) and found another workaround:
```
#[binread]
pub struct Foo {
    #[br(temp)]
    foo: binrw::NullString,
    // #[br(calc = foo)] // ERROR: borrow of moved value: `foo`
    #[br(calc = std::mem::replace(&mut foo, binrw::NullString::default()))]
    pub bar: binrw::NullString,
}
```
I also debugged the issue using cargo-expand and I think the reason for the error is that in generated `BinRead` impl after temp field is moved to calc field calls to [BinRead::after_parse](https://docs.rs/binrw/latest/binrw/trait.BinRead.html#method.after_parse) are executed for all fields (temporary too). Not sure what would be the best way to fix it.

**Comment by jam1garner** [comment]
ok so @rafalh had it most of the way, here's a working example:

```rust
#[binread]
pub struct Foo {
    #[br(temp, postprocess_now)]
    foo: binrw::NullString,
    
    #[br(calc = foo)]
    pub bar: binrw::NullString,
}

```

The `postprocess_now` is so that it doesn't call after_parse after the move (it will call it immediately after reading). I'm going to open another issue though because I think an attribute for "don't call after_parse" is needed.

Very silly mistake on my part, thank you both for bringing this to my attention :)

**Comment by jam1garner** [comment]
Oh an a little fun fact for another workaround for you: if you want to omit `after_parse` calls entirely, you can use `#[br(map = |x| x)]`, as `map`-ing a field disables `after_parse` being called

(Still going to make that issue for having proper support for disabling after_parse)

**Comment by crlf0710** [comment]
thanks!
