### ISSUE TITLE
Add `br(map_reader)` attribute

### ISSUE THREAD

**Issue by jam1garner** [jam1garner/binrw#121]
### Motivation

Being able to utilize reader adapters easily would greatly improve multiple areas of binrw that could use a bit of improvement:

* Parsing from decompressed or encrypted content
* Ensuring a field doesn't read past a specific size
* Easier "parse until end of section" ability (something akin to the `.take(...)` io::Read adapter[^1])

[^1]: `io::Take` does not support seeking so this functionality would also be needed (likely 2 variants, one for "seeks relative to current position" and one for "seeks relative to start of inner reader")

### Syntax

```rust
#[br(map_reader = $map_fn:expr)]
```

**Comment by csnover** [comment]
I feel like this, or something very similar, would also be the correct solution for issues like #102.
