### ISSUE TITLE
NullString::to_string can panic

### ISSUE THREAD

**Issue by vthib** [jam1garner/binrw#131]
Thanks for your work on binread/binrw!

I stumbled upon some unexpected panics inside binread, when calling `NullString::to_string`, which calls `std::str::from_utf8` and unwraps the result.

This is unexpected and quite different from the behavior for `NullWideString`, as well as from the implementations of the `into_string` methods, and from a user point of view, a call to `to_string` is not expected to be able to panic at all.

I can see two possible fixes:
- Remove those `ToString` implementations. I actually replaced them with calls to `into_string()`, and i'm not sure how useful they are.
- Fix the `ToString` implementation for `NullString` to do: `String::from_utf8_lossy(self).to_string()`.

What is your opinion on this?

**Comment by jam1garner** [comment]
Thanks for raising this concern, changed it to be lossy rather than panic in 0.9.2
