### ISSUE TITLE
How about the support for Open ended byte arrays: [u8]?

### ISSUE THREAD

**Issue by alligatorme** [jam1garner/binrw#159]
I have a struct for binread derive in which the only unsized field (Vec<u8>) alway located in last item but no array length afford,
`
#[derive(BinWrite,BinRead,Debug)]
pub struct PingRequest {

      pub pk: Key,
      pub nonce: Nonce,
      pub payload: Vec<u8>,
 }

`
just like the description of open ended bytes array in binary_layout (https://crates.io/crates/binary-layout).
How about support such kind of struct without  array length?

**Comment by MrNbaYoh** [comment]
You can use the [binrw::until_eof](https://docs.rs/binrw/latest/binrw/fn.until_eof.html) parser to read until the end of the input stream. Take a look at the example given in the documentation linked above.
