### ISSUE TITLE
Feature: binrw-io

### ISSUE THREAD

**Issue by dmgolembiowski** [jam1garner/binrw#176]
## Description

It's currently a bit clunky to go back and forth between a `binrw::Cursor` (or `io::Cursor`) and one of the dozens of ways you can write bytes to a socket. 

For instance, if you're hoping to send a deserialized `T`, where `T: BinWrite`, I think it ends up looking like this:

```rs
let addr = SocketAddrV4::new(Ipv4Addr::new([192, 168, 1, 10]), 4433);
match TcpStream::connect(addr) {
    Ok(mut stream) => {
        let mut buffer = Vec::<u8>::new();
        Cursor::new(&mut buffer).write_be::<BinrwThing>(&b).unwrap();
        stream.write(&buffer);
    },
    _ => panic!("..."),
}
```

This is fine. But I don't think it's terribly obvious, and think it would be better if there was an opt-in way to derive `BinrIo` and/or `BinwIo`, which supplies convenient trait implementations for going `.into()` a `TcpStream`, `UnixDatagram`, `mio::<thing>`, etc etc.

**Comment by csnover** [comment]
Is there some reason why the [`NoSeek`](https://docs.rs/binrw/latest/binrw/io/struct.NoSeek.html) adaptor is not working for you?

**Comment by csnover** [comment]
Hi! Could you please provide an answer to the previous question? I’ll close this ticket if there’s no response soon. Thanks!

**Comment by dmgolembiowski** [comment]
> Is there some reason why the [`NoSeek`](https://docs.rs/binrw/latest/binrw/io/struct.NoSeek.html) adaptor is not working for you to write directly to the stream?

Thanks for responding. I'd like to explore `NoSeek` first if that's alright? It's not immediately familiar to me, but if you're gracious enough to dig out the link then I'll trust your expertise. Thank you! 😄
