### ISSUE TITLE
Support try on struct level

### ISSUE THREAD

**Issue by mpe85** [jam1garner/binrw#180]
Would it be possible to support the `try` attribute on struct level, so that it is applied to all fields inside the struct?
I have a lot of structs where all fields have the `try` attribute, so it would be very neat to have this possibility.
Thanks.

**Comment by csnover** [comment]
Hi! Sorry about missing this until now, I have had some issues with GH notifications and this slipped by. If you are still interested in this feature, are you able to say a little more about the data format you are parsing where all the fields in a struct may not exist? It is possible to add a struct-level directive but it is also possible that there might be different solution that works better.

**Comment by csnover** [comment]
Hi! I’m going to close this issue for now due to non-response. Apologies again about the delay. If you still would like to see this feature in future, please reply any time with the requested information and it can be reopened. Thanks!
