### ISSUE TITLE
#[br(dbg)] doesn't work when pad_before directive is also used

### ISSUE THREAD

**Issue by crjennette** [jam1garner/binrw#188]
When the debug attribute `#[br(dbg)]` is used for a field in the same struct as a `#[br(pad_before=N)]` attribute, the offset printed to output is incorrect.

When the following is used, the offsets printed would be 0x00, 0x04, and 0x08; but they should be 0x00, 0x08, and 0x0c.

```rust
#[derive(Debug)]
#[binrw]
struct Header{
    #[br(dbg)]
    field1: u32,
    #[br(dbg)]
    #[br(pad_before=4)]
    field2: u32,
    #[br(dbg)]
    field3: u32
}
```

**Comment by csnover** [comment]
Thanks for your report, and sorry for the delay. This will be fixed in the next release.
