### ISSUE TITLE
Add Vec<T> read-until-EOF and read-until-condition

### ISSUE THREAD

**Issue by csnover** [jam1garner/binrw#20]
* Read until EOF: https://github.com/jam1garner/binread/issues/36
* Read until user-defined condition (terminator, etc.): https://github.com/jam1garner/binread/issues/34

This blocks on #5 since the primary use case for named arguments is to enable better direct passing of options to support stuff like this instead of requiring parser changes for type-specific feature enhancements.

**Comment by jam1garner** [comment]
Added to binrw 0.6.0, albeit in a different form than was proposed. See [`until`](https://docs.rs/binrw/0.6.0/binrw/fn.until.html) and [`until_eof`](https://docs.rs/binrw/0.6.0/binrw/fn.until_eof.html)
