### ISSUE TITLE
Cannot use binrw 0.12.0

### ISSUE THREAD

**Issue by Talon1024** [jam1garner/binrw#224]
I can't use binrw 0.12.0. Apparently, there's a compile error with `binrw_derive`, the procedural macro crate for binrw:

    Compiling binrw_derive v0.12.0
    error[E0599]: no method named `source_text` found for struct `proc_macro2::Span` in the current scope
      --> /home/~~~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/binrw_derive-0.12.0/src/binrw/backtrace/mod.rs:32:39
       |
    32 |         if let Some(text) = self.span.source_text() {
       |                                       ^^^^^^^^^^^ method not found in `Span`
    
    For more information about this error, try `rustc --explain E0599`.
    error: could not compile `binrw_derive` (lib) due to previous error

**Comment by csnover** [comment]
Could you please give the version of rustc you are using? Thanks!

**Comment by Talon1024** [comment]
Rustc 1.72.1, stable toolchain

**Comment by csnover** [comment]
OK. Please try running `cargo update` and try again. I guess that you have a very old proc-macro2 dependency and the dependency list was not updated with a correct minimum version for the API that binrw uses. I will be committing changes to specify new minimums. Please let me know how it goes. Thanks!
