### ISSUE TITLE
How to use a FilePtr to a vector, where the item count is defined after the pointer.

### ISSUE THREAD

**Issue by Noja13it** [jam1garner/binrw#38]
So I have a binary file format I'm trying to implement. And in this fileformat I have data structured like this:

```rust
pub struct Data {
    pub version: u32,

    pub tables_offset: i32, 

    pub number_of_tables: i32,

    ...
}
```

Now, preferably I'd like to use something like this:

```rust 
pub struct Data {
    pub version: u32,

    #[br(count=number_of_tables, parse_with=FilePtr::<i32, Vec<Table>>::parse)]
    pub tables: Vec<TableInfo>,

    pub number_of_tables: i32,

    ...
}
```

Which, of course, isn't working because `number_of_tables` is defined *after* the pointer.

Is there a way I can acomplish this? I figure maybe I can store both pointer and count in temporary variables and then read the tables, but I'm not sure how I would send arguments to a custom parser to do that.

**Comment by Noja13it** [comment]
Ok, never mind, I figured out I could just parse both the pointer and count inside the custom parser since they're adjacent.. No need to send them as arguments.

**Comment by jam1garner** [comment]
also sorry I missed this @Noja13it, for future reference help questions like this are a good fit for our discord/matrix chat as people notice and get back to you faster :)
