### ISSUE TITLE
Add no_std implementation of io::Write for io::Cursor

### ISSUE THREAD

**Issue by jam1garner** [jam1garner/binrw#43]
Implementation instructions:

All the work that's needed will be in [this file](https://github.com/jam1garner/binrw/blob/master/binrw/src/io/no_std/cursor.rs).

Add `Write` to the import at the top and then implement it for:

* `Cursor<&mut [u8]>`
* `Cursor<&mut Vec<u8>>`
* `Cursor<Vec<u8>>`
* `Cursor<Box<[u8]>>`

Why specifically these individual types and not something more generic like `AsMut<[u8]>`? Well... the implementations for `Vec` (and `&mut Vec`) allow for appending data (which `AsMut<[u8]>` wouldn't be able to do while also conflicting with any special-cased `Vec` implementation that could be written).

Even the standard library itself has the issue (and it's the interface we need to be compatible against anyways):

![image](https://user-images.githubusercontent.com/8260240/132117136-930bc5aa-f9cf-46d9-a03d-784b9d30d417.png)

the actual implementations should be rather straightforward and can likely be mostly a copy/paste job from std ([source for std implementation](https://doc.rust-lang.org/src/std/io/cursor.rs.html#320-472))

If anyone wants to tackle this issue but needs help feel free to contact me on discord

**Comment by dmgolembiowski** [comment]
I can't currently compile anything using cargo atm b/c of my VPN, but is this about what you're looking for?
https://github.com/dmgolembiowski/binrw/blob/feature-42-add-binrw-attribute-macro/binrw_derive/src/binrw_attr.rs
