### ISSUE TITLE
Reading a C-like enum with magics of different types no longer compiles

### ISSUE THREAD

**Issue by jam1garner** [jam1garner/binrw#49]
```rust
#[binread]
enum Test {
    #[br(magic = b"abc")] // <-- [u8; 3]
    Abc,

    #[br(magic = b"ab")] // <-- [u8; 2]
    Ab,

    #[br(magic = b"a")] // <-- [u8; 1]
    A,
}
```

At some point while re-organizing, the above has stopped working. This type is non-trivial to handle as it requires storing the start position and restarting for each variant.

Relevant location of the code:

https://github.com/jam1garner/binrw/blob/2e73f333950c34975514c3a565bbce73951e675c/binrw_derive/src/codegen/read_options/enum.rs#L63-L89

The solution should not involve removing the above code, as it was derived from the fast-path of the previous code, but rather first checking if all the magic literal types (including byte string lengths) are identical (and if so continue using the above code as it will be much faster).

If not all literal types are the same, each type should attempt to be parsed one after another until one successfully parses. The general structure can be borrowed from the following code:

https://github.com/jam1garner/binrw/blob/2e73f333950c34975514c3a565bbce73951e675c/binrw_derive/src/codegen/read_options/enum.rs#L139-L148

**Comment by dmgolembiowski** [comment]
To get a vibe check, I'd like to critically examine this section:
> The solution should not involve removing the
> above code, as it was derived from the fast-path
> of the previous code, but rather first checking if all
> the magic literal types (including byte string
> lengths) are identical (and if so continue using the
> above code as it will be much faster).

It seemingly hinges on the assumption that the fast-path code was infallible — airtight even. What can we demonstrate to prove or disprove this statement?

Next, what was the original commit SHA that results in this error occurring? Can we isolate a point in time where it didn't happen?
