### ISSUE TITLE
Port dbg attribute to modern binrw

### ISSUE THREAD

**Issue by jam1garner** [jam1garner/binrw#50]
The br(dbg) attribute was an attribute I proposed a while back that never actually landed on master. I would still be interested in it, and for the most part the process of porting it to work using the current codebase shouldn't actually require significant changes.

Original PR to base this off: https://github.com/jam1garner/binrw/pull/16

Effectively the goal is to port or reimplement the contents of the PR. If there's any trouble with it feel free to message me in the discord/matrix chat.

**Comment by csnover** [comment]
Resolved by https://github.com/jam1garner/binrw/pull/162.
