### ISSUE TITLE
Verify that all documentation links are correct/working

### ISSUE THREAD

**Issue by jam1garner** [jam1garner/binrw#65]
See the following comment:

https://github.com/jam1garner/binrw/issues/7#issuecomment-930539560

**Comment by CuriousTommy** [comment]
The Calculations header is misspelled as "Caculations"

https://docs.rs/binrw/0.8.0/binrw/attribute/write/index.html#caculations

**Comment by csnover** [comment]
Since I was the one who did the work it means there are probably some documentation links that are still broken, but I did my best to find and fix all of them and so everything on the master branch should always go to somewhere, instead of sometimes going to nowhere.
