### ISSUE TITLE
f64 field reading as u64

### ISSUE THREAD

**Issue by ratal** [jam1garner/binrw#81]
Hi @jam1garner ,
Thanks for this crate, it is super efficient as I have many structures/headers in the file I want to parse (26 in total with various complexity, using byteorder or nom would be crazy). One example:
```
#[derive(Debug, Clone, BinRead)]
#[br(little)]
pub struct Cc4Block {
    cc_id: [u8; 4], 
    reserved: [u8; 4],
    cc_len: u64,
    cc_links: u64, 
    cc_tx_name: i64, 
    cc_md_unit: i64, 
    cc_md_comment: i64,
    cc_cc_inverse: i64,
    #[br(if(cc_links > 4), little, count = cc_links - 4)]
    pub cc_ref: Vec<i64>,
    pub cc_type: u8, 
    cc_precision: u8, 
    cc_flags: u16, 
    cc_ref_count: u16, 
    cc_val_count: u16, 
    cc_phy_range_min: f64, 
    cc_phy_range_max: f64, 
    #[br(if(cc_val_count > 0 && cc_type < 11), little, count = cc_val_count)]
    pub cc_val_real: Vec<f64>, 
    #[br(if(cc_val_count > 0 && cc_type == 11), little, count = cc_val_count)]
    pub cc_val_uint: Vec<u64>,
}
```
In this case, parsing goes correctly but the f64 values are actually read as u64 (vect or not). For instance, I have 4598571536312485020 instead of 0.5
I used cargo expand to understand what could go wrong but the variables are properly declared as f64.
I tried also with BinRead and behavior is same -> issue is at a lower level, but I cannot figure out where from the expanded code. Would you have any advice ?

Second point, minor issue, while I was trying to switch from binread to binrw, the rust-analyzer is giving me errors which are actually not raised at compile : 

> range end index 8 out of range for slice of length 4

I guess this is related to the array [u8; 4]

**Comment by ratal** [comment]
Thanks,
Depending of cc_type value (<11), type to be considered for cc_val is different, real or uint. Having 2 fields is the only way I found to overcome this.
I tried again with a 'rustup update stable' + a restart in the mean time and the values are now ok...
Just in case and for your info, I granted you access to a private (for the moment) repo from where you could try to reproduce the issue, in tests.rs, info_test() (uncompressing test files needed). Mostly with test_mdf4.mf4.

**Comment by jam1garner** [comment]
OH I was wondering what the invite was from. Honestly thought it was some new type of spam >_> (sorry)

wish I knew which version you were on before, that sounds like a super weird issue with Rust itself! I'm glad it resolved itself though, if you have any other issue feel free to re-open this issue or make a new one.

Also @ratal, minor tip, using an enum + `pre_assert` might clean up `cc_val`:

```rust
#[derive(Debug, Clone, BinRead)]
#[br(little)]
pub struct Cc4Block {
    // ...     
    #[br(args{ count: cc_val_count, cc_type })]
    pub cc_vals: CcValList,
}

#[derive(Debug, Clone, BinRead)]
#[br(little, args { count: u16, cc_type: u8 })]
pub enum CcValList {    
    #[br(pre_assert(cc_type < 11))]
    Real(#[br(count = count)] Vec<f64>),

    #[br(pre_assert(cc_type == 11))]
    Uint(#[br(count = count)]  Vec<u64>),
}
```

(above code snippet is untested but should be a mostly-functioning outline of what I mean)
