### ISSUE TITLE
Add field-level `repr` for bi-directional conversion using `From`/`Into`

### ISSUE THREAD

**Issue by jam1garner** [jam1garner/binrw#92]
For example, NullString <-> String conversion is quite common (as NullString isn't a very useful type in-memory).

Proposed syntax by actioninja:

```rust
#[brw(as(NullString))]
name: String,
```

**Comment by octylFractal** [comment]
Suggestion: re-use the `repr` attribute for this purpose. It already partially indicates this type of state.

**Comment by jam1garner** [comment]
Implementation Instructions:

1. Since `repr($ty)` is ultimately desugaring to a mapping (using `TryInto` to do the mapping from representation-type to in-memory type, or vice-versa) we'll want to add a new way to convert to [`Map`](https://github.com/jam1garner/binrw/blob/dfc15d3be9f6ac3b41da81f2f3e3e417daed3b1c/binrw_derive/src/parser/types/map.rs#L7). Our parsing system has a built-in way to do this, just add `Repr` to the [`#[from(...)]` line](https://github.com/jam1garner/binrw/blob/aa1281e3642d0f55bab03137c230c408d6bb8e4b/binrw_derive/src/parser/read/field_level_attrs.rs#L25) and implement `From<Repr> for Map`. Since we're using `TryInto` (fallible) we're going to want to have our `From` implementation convert into a `Map::Try`.
2. For the implementation of `From`, we'll want to use `quote!{}` in order to generate a closure that looks something like:
```rust
let ty = &field.ty;
quote! {
    |repr_in| {
        <#ty as core::convert::TryInto>::try_into(repr_in)
            .map_err(|err| ::binrw::Error::ConvertFail { pos: #POS, err: Box::new(err) as Box<dyn CustomError> })
    }
}
```
3. Add the previously mentioned new `ConvertFail` variant to `binrw::Error`. I think the only fields it needs are `pos` (u64) and `err` (`Box<dyn CustomError>`), however you're free to think of how that could be changed, and more bikeshedding can be done at review time.
4. Repeat step #2 but for `write::Repr` instead of `read::Repr`. The closure body will need to be flipped (probably using `TryFrom` so you can still specify the type since we have that available to us)

**Comment by dmgolembiowski** [comment]
Does this introduce a naming conflict with [`binrw/src/io/no_std/error.rs`](https://github.com/jam1garner/binrw/blob/aa1281e3642d0f55bab03137c230c408d6bb8e4b/binrw/src/io/no_std/error.rs#L9) or would these be one in the same?

**Comment by jam1garner** [comment]
@dmgolembiowski the enum you're referring to is a private implementation detail of that module and is unrelated
